### ISSUE TITLE
before ::fulfillRandomWords patrick got the exactly name ,but i am not

### ISSUE THREAD

**Issue by Web3ILoveQier** [Cyfrin/foundry-smart-contract-lottery-cu#66]
This patric got name:
![image](https://github.com/user-attachments/assets/bf76e7d2-aad1-4907-880d-c5c02f1f3e81)

This is my got name:
![image](https://github.com/user-attachments/assets/0c9646bf-3905-4ed4-bf6f-69db00e6a4c0)

why he can get the fullname but i can not?

**Comment by Equious** [comment]
I would assume this is just a change to the versions of the error output. If that address pertains to your VRF Coordinator, it's effectively the same.
