### ISSUE TITLE
Foundry doesn't accept default sender as deployer.

### ISSUE THREAD

**Issue by andrei2308** [Cyfrin/foundry-smart-contract-lottery-cu#68]
---

### **Title: Improve Deployment to Use `msg.sender` Dynamically**

---

### **Description**

When running the current code, I encountered an issue where the default Foundry sender address (`0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`) was hardcoded into the `HelperConfig.s.sol` file. This caused errors when deploying the contract with a specified sender using the `--sender` flag. The deployment would still rely on the default Foundry sender address, making the specified sender ineffective.

To address this issue, the default Foundry sender address should be replaced with `msg.sender`. This change would allow the deployer address to be dynamically captured during deployment and set in `HelperConfig.s.sol`.

---

### **Proposed Solution**

1. **Capture the Deployer Address Dynamically**:
   - In `DeployRaffle.s.sol`, store `msg.sender` in a variable and use it as the deployer address.

2. **Update `HelperConfig.s.sol`**:
   - Replace the hardcoded default Foundry sender address with the dynamically captured deployer address passed from `DeployRaffle.s.sol`.

3. **Run Command**:
   - Update the deployment command to specify the sender address dynamically:
     ```bash
     forge script script/DeployRaffle.s.sol:DeployRaffle \
       --rpc-url $RPC_URL \
       --sender <SENDER ADDRESS> \
       --account <ACCOUNT NAME> \
       --broadcast
     ```
     - **`<SENDER ADDRESS>`**: An address from Anvil.
     - **`<ACCOUNT NAME>`**: The wallet name storing the private key affiliated with the `<SENDER ADDRESS>`.

---

### **Steps to Reproduce**

1. Run the deployment command with a specific sender:
   ```bash
   forge script script/DeployRaffle.s.sol:DeployRaffle \
     --rpc-url $RPC_URL \
     --sender <SENDER ADDRESS> \
     --broadcast
   ```

2. Observe that the deployment still uses the Foundry default sender address (`0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`), as it is hardcoded in `HelperConfig.s.sol`.

---

### **Expected Behavior**

The deployment should use the address specified with the `--sender` flag, and this address should be dynamically passed to `HelperConfig.s.sol`.

---

### **Additional Notes**

- The issue arises because `HelperConfig.s.sol` directly references the hardcoded default sender address. Replacing it with `msg.sender` during deployment ensures that the deployer address is correctly set and avoids reliance on the Foundry default sender.

**Comment by andrei2308** [comment]
For more info on how to solve this you can check my repository where I made the necessary changes : https://github.com/andrei2308/foundry-raffle-smart-contract

**Comment by Equious** [comment]
Please consider submitting a PR detailing changes.
